### ISSUE TITLE
Panic crashes the exporter and woke me UP 

### ISSUE THREAD

**Issue by hectorj2f** [giantswarm/prometheus-pingdom-exporter#8]
The prometheus pingdom exporter whose name is quite descriptive (ironically), crashed at night twice. Incident's link https://gigantic.slack.com/archives/incidents/p1475632225000683

We should improve it: 1) Restart on-failure 2) Hunting and fixing the origin of this panic.

```
Oct 05 01:44:00 0b04f612c4d4826f systemd[1]: Started prometheus-pingdom-exporter Service.
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x534be8]
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: goroutine 36 [running]:
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: panic(0x778b80, 0xc420012030)
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: github.com/russellcardullo/go-pingdom/pingdom.(*CheckService).List(0xc420134020, 0x0, 0x0, 0x0, 0x0, 0x0)
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: /usr/code/.gobuild/src/github.com/russellcardullo/go-pingdom/pingdom/check.go:32 +0x108
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: github.com/giantswarm/prometheus-pingdom-exporter/cmd.serverRun.func1(0xc42014e180)
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: /usr/code/.gobuild/src/github.com/giantswarm/prometheus-pingdom-exporter/cmd/server.go:76 +0x65
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: created by github.com/giantswarm/prometheus-pingdom-exporter/cmd.serverRun
Oct 05 01:45:32 0b04f612c4d4826f docker[21105]: /usr/code/.gobuild/src/github.com/giantswarm/prometheus-pingdom-exporter/cmd/server.go:133 +0xca
```

ping @giantswarm/team-positive

**Comment by xh3b4sd** [comment]
I think this will be fixed by https://github.com/russellcardullo/go-pingdom/pull/5.

**Comment by JosephSalisbury** [comment]
See also https://github.com/giantswarm/prometheus-feeder/issues/29

**Comment by oponder** [comment]
Assuming this is no longer an issue.
